/**
 * tools/extract_palettes.mjs — skinprofile.html → data/palettes.json
 * ---------------------------------------------------------------------------
 * skinprofile.html holds the curated 12-palette system inline (so the page
 * works with no fetch and no module). That inline PALETTES object stays the
 * single source of truth — this tool copies it into data/palettes.json so the
 * Colourist and the fabric tools can read it without parsing HTML.
 *
 * Re-run after editing the palettes in skinprofile.html:
 *     node tools/extract_palettes.mjs
 */
import fs from 'fs';

const SRC = 'skinprofile.html';
const OUT = 'data/palettes.json';

const html  = fs.readFileSync(SRC, 'utf8');
const start = html.indexOf('const PALETTES = {');
if (start === -1) throw new Error(`PALETTES object not found in ${SRC}`);
const end = html.indexOf('\n        };', start);
if (end === -1) throw new Error(`could not find the end of PALETTES in ${SRC}`);

const literal  = html.slice(start + 'const PALETTES = '.length, end + '\n        }'.length);
const PALETTES = eval('(' + literal + ')');   // trusted, first-party source file

// Shape check: 4 skin types × 3 undertones, five colours in every tier.
const SKIN_TYPES = ['fair-light', 'medium-olive', 'tan', 'dark-deep'];
const UNDERTONES = ['cool', 'warm', 'neutral'];
const TIERS      = ['best', 'acceptable', 'bestCombos', 'haCombos'];

const problems = [];
for (const skin of SKIN_TYPES) {
  if (!PALETTES[skin]) { problems.push(`missing skin type: ${skin}`); continue; }
  for (const under of UNDERTONES) {
    const p = PALETTES[skin][under];
    if (!p) { problems.push(`missing ${skin}/${under}`); continue; }
    for (const tier of TIERS) {
      if (!Array.isArray(p[tier])) problems.push(`${skin}/${under}: ${tier} is not an array`);
      else if (p[tier].length !== 5) problems.push(`${skin}/${under}: ${tier} has ${p[tier].length} entries, expected 5`);
    }
  }
}
if (problems.length) {
  console.error('Palette data problems:\n  ' + problems.join('\n  '));
  process.exit(1);
}

const out = {
  generated: new Date().toISOString(),
  source: SRC,
  note: 'Generated by tools/extract_palettes.mjs — edit skinprofile.html, not this file.',
  skinTypes: SKIN_TYPES,
  undertones: UNDERTONES,
  palettes: PALETTES,
};
fs.writeFileSync(OUT, JSON.stringify(out, null, 2));

const colours = SKIN_TYPES.length * UNDERTONES.length * 5;
console.log(`✓ ${OUT} — 12 palettes, ${colours} best + ${colours} acceptable colours, ${colours * 2} pairings`);
